(in-package :test)

(load "compute.lisp")

(defun test ()
  (assert (= (compute:levenshtein "Sunday" "Saturday") 3))
  (assert (= (compute:levenshtein "kitten" "sitting") 3))
  (assert (= (compute:levenshtein "rosettacode" "raisethysword") 8))
  (assert (= (compute:levenshtein "back" "book") 2))
  (assert (= (compute:levenshtein "hello" "hell") 1))
  (assert (= (compute:levenshtein "hell" "hello") 1))
  (assert (= (compute:levenshtein "kitten" "") 6))
  (assert (= (compute:levenshtein "kitten" "k") 5))
  (assert (= (compute:levenshtein "k" "") 1))
  (assert (= (compute:levenshtein "" "") 0))
  (assert (= (compute:levenshtein "kit" "") 3))
  (princ "All tests passed!"))
